version: 2
updates:
  # Maintain dependency of Python App Docker image
  - package-ecosystem: "docker"
    directory: "/python-app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Asia/Singapore"
    labels:
      - "dependencies"
      - "dockerfile"
    commit-message:
      prefix: "(dockerfile) "
    assignees:
      - "bellyliu"
  
  - package-ecosystem: "pip"
    directory: "/python-app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Asia/Singapore"
    # Grouping: Bundles all minor/patch updates into one PR
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "minor-or-patch"
      - "pip"
    commit-message:
      prefix: "(pip) "
    assignees:
      - "bellyliu"
  
  # PR for Major update won't be grouped
  - package-ecosystem: "pip"
    directory: "/python-app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Asia/Singapore"
    ignore:
      - update-types: 
          - version-update:semver-patch
          - version-update:semver-minor
    labels:
      - "major"
      - "pip"
    commit-message:
      prefix: "(pip) "
    assignees:
      - "bellyliu"
