version: 2
updates:
  # Maintain dependency of Jenkins Pipeline
  - package-ecosystem: "docker"
    directory: "pipeline"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Asia/Singapore"
    labels:
      - "dependencies"
      - "pipeline"
    commit-message:
      prefix: "[pipeline] "
    assignees:
      - "bellyliu"
