config:
  namespace: argocd

argo-cd:
  global:
    domain: argocd.skordev.com
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.14.11"

  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

    config:
      admin.enabled: 'true'
      params:
        server.insecure: "true"